const BASE_FEATURES = {
  maintenance: true,
  warranty: true,
  serviceJobs: true,
  returns: true,
  accessories: true,
  thirdParty: true,
  paxPrimary: false,
  contractTracking: false,
  consumableStock: true,
  riders: false,
  individualAvailability: false,
  attendance: false,
  conditionQc: true,
  dispatchReturn: true,
  subSpaces: false,
  warehouse: true,
};

const BASE_DATES = ["travel_day", "setup_date", "technical_date", "shoot_date", "off_day", "end_day", "return_day"];
const NO_RETURN_DATES = ["setup_date", "technical_date", "shoot_date", "off_day", "end_day"];

const COMMON = {
  eventTitle: "Event",
  bookingLabel: "Booking",
  crewLabel: "Crew",
  personnelLabel: "Personnel",
};

const equipmentTypes = [
  ["device", "Device - standalone bookable unit"],
  ["accessory", "Accessory - travels with a device"],
  ["kit", "Kit - named collection (auto-expands in booking)"],
  ["bundle", "Bundle - pre-packaged multi-device set"],
  ["third_party_equipment", "Third-Party Equipment - rented from vendor"],
  ["consumable", "Consumable - stock-depleted item"],
];

const baseReplacements = [
  ["Shoots", "Events"], ["shoots", "events"], ["SHOOTS", "EVENTS"],
  ["Shoot", "Event"], ["shoot", "event"], ["SHOOT", "EVENT"],
];

function profile({
  value,
  label,
  addLabel,
  registryLabel,
  resourceLabel,
  resourcePlural,
  utilizationLabel,
  complianceLabel,
  serviceLabel,
  conflictLabel,
  returnLabel,
  thirdPartyLabel,
  operationsLabel,
  vendorsLabel,
  features,
  itemTypes,
  replacements = [],
  extraFields = {},
  documents = {},
  dateTypes,
  workflow = {},
}) {
  return {
    ...COMMON,
    value,
    label,
    addLabel,
    registryLabel,
    resourceLabel,
    resourcePlural,
    utilizationLabel,
    complianceLabel,
    serviceLabel,
    conflictLabel,
    returnLabel,
    thirdPartyLabel,
    operationsLabel,
    vendorsLabel,
    features: { ...BASE_FEATURES, ...features },
    itemTypes,
    replacements: [...baseReplacements, ...replacements],
    extraFields,
    documents: {
      gatePass: "Gate Pass",
      jobCard: "Job Card",
      challan: "Road Challan",
      manpower: "Manpower Sheet",
      damage: "Damage Report",
      ...documents,
    },
    dateTypes: dateTypes || BASE_DATES,
    workflow,
  };
}

export const BOOKING_PROFILES = [
  profile({
    value: "equipment",
    label: "Equipment Booking",
    addLabel: "Additions",
    registryLabel: "Master Registry",
    resourceLabel: "Equipment",
    resourcePlural: "Equipment",
    utilizationLabel: "Equipment Utilization",
    complianceLabel: "Warranty Expiring Soon",
    serviceLabel: "Equipment in Service",
    conflictLabel: "Equipment conflicts",
    returnLabel: "Returns due today",
    thirdPartyLabel: "3rd Party Equipment",
    operationsLabel: "Papers & QC",
    vendorsLabel: "Vendors & Procurement",
    itemTypes: equipmentTypes,
    defaultCategories: ["Camera", "Lens", "Audio", "Lighting", "Power", "Support / Rigging", "Grip", "Storage / Media", "Transmission", "Cables / Accessories", "IT / Compute", "Other"],
    extraFields: {
      inventory: [
        { label: "Calibration notes", key: "calibration_notes", type: "text" },
        { label: "Insurance policy number", key: "insurance_policy", type: "text" },
        { label: "Replacement value (₹)", key: "replacement_value", type: "text" },
      ],
    },
  }),
  profile({
    value: "artist",
    label: "Artist Booking",
    addLabel: "Add Artist",
    registryLabel: "Artist Registry",
    resourceLabel: "Artist",
    resourcePlural: "Artists",
    utilizationLabel: "Artist Booking Load",
    complianceLabel: "Contracts / Riders Pending",
    serviceLabel: "Artist Holds",
    conflictLabel: "Artist conflicts",
    returnLabel: "Follow-ups due today",
    thirdPartyLabel: "External Artists",
    operationsLabel: "Contracts & Riders",
    vendorsLabel: "Agencies & Managers",
    features: { maintenance: false, warranty: false, serviceJobs: false, returns: false, accessories: false, warehouse: false, contractTracking: true, riders: true, individualAvailability: true, conditionQc: false, dispatchReturn: false, consumableStock: false },
    itemTypes: [["device", "Solo Artist"], ["kit", "Band / Group"], ["bundle", "Artist Package"], ["third_party_equipment", "External Artist / Agency"]],
    defaultCategories: ["Bollywood", "Sufi / Ghazal", "Classical / Hindustani", "Folk / Regional", "Rock / Pop", "EDM / Electronic", "Jazz / Blues", "Hip-Hop / Rap", "Stand-up Comedy", "Dance / Choreography", "Instrumental", "Multi-genre"],
    dateTypes: NO_RETURN_DATES,
    documents: { gatePass: "Performance Call Sheet", jobCard: "Show Brief / Technical Rider", challan: "Travel Sheet", damage: "Cancellation / No-Show Report" },
    extraFields: {
      inventory: [
        { label: "Genre / Category", key: "genre", type: "datalist", options: ["Bollywood", "Sufi / Ghazal", "Classical / Hindustani", "Folk / Regional", "Rock / Pop", "EDM / Electronic", "Jazz / Blues", "Hip-Hop / Rap", "Stand-up Comedy", "Dance / Choreography", "Instrumental", "Multi-genre"] },
        { label: "Performance Type", key: "performance_type", type: "select", options: ["", "Live Singer", "Band / Group", "DJ", "Dancer", "Comedian", "Anchor / Host", "Motivational Speaker", "Classical Instrumentalist", "Magician / Illusionist", "Other"] },
        { label: "Primary Language", key: "language", type: "select", options: ["", "Hindi", "English", "Punjabi", "Tamil", "Telugu", "Kannada", "Marathi", "Bengali", "Gujarati", "Multi-lingual", "Other"] },
        { label: "Performance Duration", key: "performance_duration", type: "select", options: ["", "15 mins", "30 mins", "45 mins", "60 mins", "90 mins", "120 mins", "180 mins", "As per show requirement"] },
        { label: "Base Fee / Day Rate (₹)", key: "base_fee", type: "text" },
        { label: "Agent / Manager Contact", key: "agent_contact", type: "text" },
        { label: "Contract Expiry Date", key: "contract_expiry", type: "date" },
        { label: "Blackout Dates", key: "blackout_dates", type: "text" },
        { label: "Technical Rider Requirements", key: "technical_rider", type: "textarea" },
        { label: "Hospitality Rider Requirements", key: "hospitality_rider", type: "textarea" },
        { label: "Travel Requirements", key: "travel_requirements", type: "text" },
        { label: "Playlist / Set List Attachment", key: "playlist", type: "text" },
      ],
      booking: [
        { label: "Performance Slot", key: "performance_slot", type: "datalist", options: ["Opening Act", "Mid-show", "Headline / Closing", "Background Music", "Cocktail Hour", "Custom"] },
        { label: "Green Room Requirement", key: "green_room", type: "select", options: ["", "Not Required", "Basic Green Room", "VIP Green Room + Hospitality", "Separate Dressing Room"] },
        { label: "Soundcheck Time", key: "soundcheck_time", type: "text" },
        { label: "Hospitality Notes", key: "hospitality_notes", type: "textarea" },
      ],
      vendor: [
        { label: "Agency Commission (%)", key: "agency_commission", type: "text" },
        { label: "Manager Contact", key: "manager_contact", type: "text" },
        { label: "Contract Template", key: "contract_template", type: "text" },
      ],
    },
    replacements: [
      ["Vendors & Procurement", "Agencies & Managers"], ["Equipment Master", "Artist Category"], ["equipment master", "artist category"],
      ["Master Registry", "Artist Registry"], ["Additions", "Add Artist"], ["Inventory", "Artist Roster"], ["inventory", "artist roster"], ["INVENTORY", "ARTIST ROSTER"],
      ["Equipments", "Artists"], ["equipments", "artists"], ["EQUIPMENTS", "ARTISTS"],
      ["Asset Code", "Artist Code"], ["Serial Number", "Contract ID"], ["Warranty Expiring Soon", "Contracts / Riders Pending"],
      ["Warranty", "Contract"], ["warranty", "contract"], ["Service Jobs", "Contract Follow-ups"], ["In Service", "On Hold"], ["in Service", "on Hold"], ["in_service", "on_hold"],
      ["Returns due today", "Follow-ups due today"], ["under repair / maintenance", "availability / booking hold"], ["Warehouse", "Availability Group"], ["warehouse", "availability group"],
      ["Equipment Utilization", "Artist Booking Load"], ["3rd Party Equipment", "External Artists"], ["Equipment in Service", "Artist Holds"], ["Equipment conflicts", "Artist conflicts"],
      ["Papers & QC", "Contracts & Riders"], ["Gate Pass", "Performance Call Sheet"], ["Job Card", "Show Brief"], ["Damage / Missing", "Cancellation / No-Show"],
      ["Equipment", "Artist"], ["equipment", "artist"], ["EQUIPMENT", "ARTIST"],
    ],
  }),
  profile({
    value: "venue",
    label: "Venue Booking",
    addLabel: "Add Venue",
    registryLabel: "Venue Registry",
    resourceLabel: "Venue",
    resourcePlural: "Venues",
    utilizationLabel: "Venue Occupancy",
    complianceLabel: "Permits / Licenses Pending",
    serviceLabel: "Venue Maintenance Holds",
    conflictLabel: "Venue conflicts",
    returnLabel: "Check-outs due today",
    thirdPartyLabel: "Partner Venues",
    operationsLabel: "Contracts & Permits",
    vendorsLabel: "Venue Partners",
    features: { warranty: false, returns: false, accessories: false, paxPrimary: true, contractTracking: true, attendance: true, subSpaces: true, dispatchReturn: false },
    itemTypes: [["device", "Room / Hall"], ["kit", "Zone / Floor"], ["bundle", "Full Venue Buyout"], ["third_party_equipment", "Partner Venue"]],
    defaultCategories: ["Banquet Hall", "Hotel Lawn / Garden", "Rooftop", "Farmhouse", "Beach / Waterfront", "Convention Centre", "Auditorium", "Open Ground", "Restaurant / Lounge", "Studio / Indoor Stage", "Mall Atrium", "Club / Bar"],
    dateTypes: NO_RETURN_DATES,
    documents: { gatePass: "Venue Access Letter", jobCard: "Event Layout / Setup Brief", challan: "Vendor Entry Pass", damage: "Venue Damage Report" },
    extraFields: {
      inventory: [
        { label: "Venue Type", key: "venue_type", type: "datalist", options: ["Banquet Hall", "Hotel Lawn / Garden", "Rooftop", "Farmhouse", "Beach / Waterfront", "Convention Centre", "Auditorium", "Open Ground", "Restaurant / Lounge", "Studio / Indoor Stage", "Mall Atrium", "Club / Bar"] },
        { label: "Indoor / Outdoor", key: "indoor_outdoor", type: "select", options: ["", "Indoor", "Outdoor", "Indoor + Outdoor", "Covered Outdoor"] },
        { label: "Capacity – Seated", key: "capacity_seated", type: "text" },
        { label: "Capacity – Theatre Style", key: "capacity_theatre", type: "text" },
        { label: "Capacity – Cocktail / Standing", key: "capacity_cocktail", type: "text" },
        { label: "Power Load Capacity (KW)", key: "power_kw", type: "text" },
        { label: "Amenities", key: "amenities", type: "datalist", options: ["AC + Parking + Generator", "AC + Parking", "AC + Generator", "AC Only", "Basic (No AC/Parking)", "Full AV + Lighting + Generator"] },
        { label: "Parking Capacity (vehicles)", key: "parking_capacity", type: "text" },
        { label: "Setup Time Buffer (hrs)", key: "setup_buffer", type: "text" },
        { label: "Breakdown Time Buffer (hrs)", key: "breakdown_buffer", type: "text" },
        { label: "Permit / License Number", key: "permit_number", type: "text" },
        { label: "Permit Expiry", key: "permit_expiry", type: "date" },
        { label: "Sub-spaces / Rooms", key: "subspaces", type: "text" },
        { label: "Floor Plan / Layout Notes", key: "layout_notes", type: "textarea" },
      ],
      booking: [
        { label: "Expected Guest Count", key: "guest_count", type: "text" },
        { label: "Layout Style", key: "layout_style", type: "select", options: ["", "Theatre", "Classroom", "Banquet (Round Tables)", "Cocktail / Standing", "U-Shape", "Boardroom", "Hollow Square", "Custom"] },
        { label: "Vendor Entry Window", key: "vendor_entry", type: "text" },
        { label: "Check-in Coordinator", key: "checkin_coordinator", type: "text" },
      ],
    },
    replacements: [
      ["Vendors & Procurement", "Venue Partners"], ["Equipment Master", "Venue Type"], ["equipment master", "venue type"],
      ["Master Registry", "Venue Registry"], ["Additions", "Add Venue"], ["Inventory", "Venue Spaces"], ["inventory", "venue spaces"], ["INVENTORY", "VENUE SPACES"],
      ["Equipments", "Venues"], ["equipments", "venues"], ["EQUIPMENTS", "VENUES"],
      ["Warehouse", "Venue Cluster"], ["warehouse", "venue cluster"], ["Asset Code", "Venue Code"], ["Serial Number", "License No."],
      ["Warranty Expiring Soon", "Permits / Licenses Pending"], ["Warranty", "Permit"], ["warranty", "permit"], ["Returns due today", "Check-outs due today"],
      ["Equipment Utilization", "Venue Occupancy"], ["Equipment in Service", "Venue Maintenance Holds"], ["Equipment conflicts", "Venue conflicts"], ["3rd Party Equipment", "Partner Venues"],
      ["Papers & QC", "Contracts & Permits"], ["Gate Pass", "Venue Access Letter"], ["Job Card", "Event Layout Brief"], ["Road Challan", "Vendor Entry Pass"],
      ["Equipment", "Venue"], ["equipment", "venue"], ["EQUIPMENT", "VENUE"],
    ],
  }),
  profile({
    value: "decor",
    label: "Decor Booking",
    addLabel: "Add Decor",
    registryLabel: "Decor Registry",
    resourceLabel: "Decor Item",
    resourcePlural: "Decor Items",
    utilizationLabel: "Decor Utilization",
    complianceLabel: "Condition Checks Due",
    serviceLabel: "Decor Under Repair",
    conflictLabel: "Decor conflicts",
    returnLabel: "Returns due today",
    thirdPartyLabel: "Vendor Decor",
    operationsLabel: "Papers & Condition QC",
    vendorsLabel: "Decor Vendors",
    features: { warranty: false, contractTracking: false },
    itemTypes: [["device", "Decor Item"], ["accessory", "Decor Sub-item"], ["kit", "Theme Kit"], ["bundle", "Decor Package"], ["third_party_equipment", "Vendor Decor"], ["consumable", "Consumable Decor"]],
    defaultCategories: ["Floral / Garden", "Royale / Mughal", "Contemporary / Modern", "Rustic / Vintage", "Minimalist", "Bohemian", "Beach / Coastal", "Festive / Traditional", "Corporate / Branded", "Fairytale / Princess", "Lighting & Ambiance", "Backdrop / Stage"],
    documents: { damage: "Condition Report" },
    extraFields: {
      inventory: [
        { label: "Decor Theme / Style", key: "decor_theme", type: "datalist", options: ["Floral / Garden", "Royale / Mughal", "Contemporary / Modern", "Rustic / Vintage", "Minimalist", "Bohemian", "Beach / Coastal", "Festive / Traditional", "Corporate / Branded", "Fairytale / Princess", "Lighting & Ambiance", "Backdrop / Stage"] },
        { label: "Material Type", key: "material_type", type: "datalist", options: ["Fabric / Draping", "Floral / Natural", "Wood", "Metal / Brass", "Plastic / Acrylic", "Paper / Cardboard", "Glass / Crystal", "LED / Neon Lights", "Thermocol / Foam", "Mixed"] },
        { label: "Color Palette", key: "color_palette", type: "text" },
        { label: "Condition Rating", key: "condition_rating", type: "select", options: ["", "Excellent", "Good", "Fair – Minor wear", "Needs Minor Repair", "Needs Major Repair"] },
        { label: "Fragility Level", key: "fragility", type: "select", options: ["", "Low – Durable", "Medium – Handle with care", "High – Fragile"] },
        { label: "Event Theme Tag", key: "event_theme_tag", type: "datalist", options: ["Wedding", "Sangeet", "Mehndi", "Birthday", "Baby Shower", "Corporate Gala", "Product Launch", "Conference", "Engagement", "Anniversary"] },
        { label: "Customization Notes", key: "customization", type: "textarea" },
      ],
      booking: [
        { label: "Theme Brief", key: "theme_brief", type: "textarea" },
        { label: "Installation Notes", key: "installation_notes", type: "textarea" },
        { label: "Strike / Removal Notes", key: "strike_notes", type: "text" },
      ],
    },
    replacements: [
      ["Vendors & Procurement", "Decor Vendors"], ["Equipment Master", "Decor Catalogue"], ["equipment master", "decor catalogue"],
      ["Master Registry", "Decor Registry"], ["Additions", "Add Decor"], ["Inventory", "Decor Inventory"], ["inventory", "decor inventory"], ["INVENTORY", "DECOR INVENTORY"],
      ["Equipments", "Decor Items"], ["equipments", "decor items"], ["EQUIPMENTS", "DECOR ITEMS"],
      ["Asset Code", "Decor Code"], ["Serial Number", "Batch / Set No."], ["Warranty Expiring Soon", "Condition Checks Due"], ["Warranty", "Condition"], ["warranty", "condition"],
      ["Equipment Utilization", "Decor Utilization"], ["Equipment in Service", "Decor Under Repair"], ["Equipment conflicts", "Decor conflicts"], ["3rd Party Equipment", "Vendor Decor"],
      ["Papers & QC", "Papers & Condition QC"], ["Damage Report", "Condition Report"], ["Equipment", "Decor Item"], ["equipment", "decor item"], ["EQUIPMENT", "DECOR ITEM"],
    ],
  }),
  profile({
    value: "catering",
    label: "Catering Booking",
    addLabel: "Add Catering",
    registryLabel: "Catering Registry",
    resourceLabel: "Menu",
    resourcePlural: "Menus",
    utilizationLabel: "Menu Booking Load",
    complianceLabel: "Menu / FSSAI Pending",
    serviceLabel: "Prep Holds",
    conflictLabel: "Kitchen conflicts",
    returnLabel: "Final guest counts due",
    thirdPartyLabel: "Catering Partners",
    operationsLabel: "Menus & Compliance",
    vendorsLabel: "Catering Partners",
    features: { maintenance: false, warranty: false, serviceJobs: false, returns: false, accessories: false, warehouse: false, paxPrimary: true, contractTracking: true, conditionQc: false, dispatchReturn: false },
    itemTypes: [["device", "Menu Package"], ["kit", "Cuisine Station"], ["bundle", "Buffet Package"], ["consumable", "Consumable / Ingredient"], ["third_party_equipment", "Partner Caterer"]],
    defaultCategories: ["North Indian", "South Indian", "Pan-Asian / Chinese", "Continental / Italian", "Mughlai / Awadhi", "Bengali", "Rajasthani / Gujarati", "Mediterranean", "Mexican", "Multi-Cuisine Buffet", "Bakery / Desserts", "Beverages / Bar"],
    dateTypes: NO_RETURN_DATES,
    documents: { gatePass: "Kitchen Brief", jobCard: "Banquet Event Order (BEO)", challan: "F&B Delivery Challan", manpower: "Service Staff Deployment", damage: "Not applicable" },
    extraFields: {
      inventory: [
        { label: "Cuisine Type", key: "cuisine_type", type: "datalist", options: ["North Indian", "South Indian", "Pan-Asian / Chinese", "Continental / Italian", "Mughlai / Awadhi", "Bengali", "Rajasthani / Gujarati", "Mediterranean", "Mexican", "Multi-Cuisine Buffet", "Bakery / Desserts", "Beverages / Bar"] },
        { label: "Meal Type", key: "meal_type", type: "select", options: ["", "Breakfast", "Brunch", "Lunch", "Hi-Tea / Snacks", "Dinner", "Cocktail Bites", "Full Day (B+L+D)", "Custom"] },
        { label: "Service Style", key: "service_style", type: "select", options: ["", "Buffet", "Plated / À La Carte", "Live Counters", "Family Style", "Cocktail / Finger Food", "Packed Meals", "Mix (Buffet + Live Counters)"] },
        { label: "Dietary Options", key: "dietary", type: "select", options: ["", "Pure Veg", "Veg + Non-Veg", "Vegan Available", "Jain Available", "Veg + Vegan + Jain", "Non-Veg Only"] },
        { label: "FSSAI / Batch Number", key: "fssai_number", type: "text" },
        { label: "Approx. Rate per Pax (₹)", key: "rate_per_pax", type: "text" },
        { label: "Tasting Notes", key: "tasting_notes", type: "textarea" },
        { label: "Ingredient / Allergen Notes", key: "allergen_notes", type: "textarea" },
      ],
      booking: [
        { label: "Pax Count", key: "pax_count", type: "text" },
        { label: "Meal Slot", key: "meal_slot", type: "select", options: ["", "Breakfast", "Lunch", "Hi-Tea", "Dinner", "All Day"] },
        { label: "Final Pax Count Deadline", key: "pax_deadline", type: "date" },
        { label: "Veg / Jain / Allergen Count", key: "veg_count", type: "text" },
        { label: "Live Counter Requirements", key: "live_counters", type: "text" },
        { label: "Service Staff Count", key: "service_staff", type: "text" },
        { label: "Tasting Session Date", key: "tasting_date", type: "date" },
      ],
      vendor: [
        { label: "FSSAI License Number", key: "fssai_license", type: "text" },
        { label: "Kitchen Contact", key: "kitchen_contact", type: "text" },
        { label: "Service Manager", key: "service_manager", type: "text" },
      ],
    },
    replacements: [
      ["Vendors & Procurement", "Catering Partners"], ["Equipment Master", "Menu Master"], ["equipment master", "menu master"],
      ["Master Registry", "Catering Registry"], ["Additions", "Add Catering"], ["Inventory", "Menu Packages"], ["inventory", "menu packages"], ["INVENTORY", "MENU PACKAGES"],
      ["Equipments", "Menus"], ["equipments", "menus"], ["EQUIPMENTS", "MENUS"],
      ["Asset Code", "Package Code"], ["Serial Number", "FSSAI / Batch No."], ["Warranty Expiring Soon", "Menu / FSSAI Pending"], ["Warranty", "FSSAI"], ["warranty", "FSSAI"],
      ["Service Jobs", "Prep Follow-ups"], ["In Service", "In Prep"], ["in Service", "in Prep"], ["Returns due today", "Final guest counts due"], ["under repair / maintenance", "menu / prep hold"],
      ["Equipment Utilization", "Menu Booking Load"], ["Equipment in Service", "Prep Holds"], ["Equipment conflicts", "Kitchen conflicts"], ["3rd Party Equipment", "Catering Partners"],
      ["Papers & QC", "Menus & Compliance"], ["Gate Pass", "Kitchen Brief"], ["Job Card", "Banquet Event Order"], ["Road Challan", "F&B Delivery Challan"], ["Manpower Sheet", "Service Staff Deployment"],
      ["Equipment", "Menu"], ["equipment", "menu"], ["EQUIPMENT", "MENU"],
    ],
  }),
  profile({
    value: "staffing",
    label: "Staffing Booking",
    addLabel: "Add Staff",
    registryLabel: "Staff Registry",
    resourceLabel: "Staff",
    resourcePlural: "Staff",
    utilizationLabel: "Staff Utilization",
    complianceLabel: "Documents Pending",
    serviceLabel: "Availability Holds",
    conflictLabel: "Staff conflicts",
    returnLabel: "Shift close-outs due",
    thirdPartyLabel: "Freelance Staff",
    operationsLabel: "Contracts & ID Docs",
    vendorsLabel: "Staffing Agencies",
    features: { maintenance: false, warranty: false, serviceJobs: false, returns: false, accessories: false, warehouse: false, paxPrimary: true, contractTracking: true, individualAvailability: true, attendance: true, conditionQc: false, dispatchReturn: false, consumableStock: false },
    itemTypes: [["device", "Staff Member"], ["kit", "Staff Team"], ["bundle", "Shift Package"], ["third_party_equipment", "Agency Staff"]],
    defaultCategories: ["Event Manager", "Floor Manager", "Registration / Help Desk", "Security / Bouncer", "Hostess / Host", "Sound Engineer", "Light Technician", "Stage Manager", "Photographer", "Videographer", "Serving Staff / Waiter", "Driver / Logistics", "MC / Anchor", "Coordinator", "Usher"],
    dateTypes: NO_RETURN_DATES,
    documents: { gatePass: "Staff Deployment Sheet", jobCard: "Staff Briefing Document", manpower: "Shift Assignment Sheet", damage: "Attendance / Incident Report" },
    extraFields: {
      inventory: [
        { label: "Role / Designation", key: "staff_role", type: "datalist", options: ["Event Manager", "Floor Manager", "Registration / Help Desk", "Security / Bouncer", "Hostess / Host", "Sound Engineer", "Light Technician", "Stage Manager", "Photographer", "Videographer", "Serving Staff / Waiter", "Driver / Logistics", "MC / Anchor", "Coordinator", "Usher"] },
        { label: "Shift Type", key: "shift_type", type: "select", options: ["", "Full Day (10+ hrs)", "Half Day (5–6 hrs)", "Morning Shift", "Evening / Night Shift", "Event Day Only", "Custom"] },
        { label: "Dress Code / Uniform", key: "dress_code", type: "select", options: ["", "Formal (Suit / Business)", "Semi-Formal (Smart Casual)", "Traditional / Ethnic", "Uniform (Company Provided)", "Black Tie / Evening Wear", "As per event theme"] },
        { label: "ID Document Type", key: "id_doc_type", type: "select", options: ["", "Aadhaar", "PAN", "Passport", "Voter ID", "Driving Licence"] },
        { label: "ID Document Number", key: "id_doc_number", type: "text" },
        { label: "ID Document Expiry", key: "id_expiry", type: "date" },
        { label: "Skills / Certifications", key: "skills", type: "text" },
        { label: "Daily / Hourly Rate (₹)", key: "rate", type: "text" },
        { label: "Background Check Status", key: "bg_check", type: "select", options: ["", "Not Required", "Pending", "Cleared", "Failed"] },
        { label: "Emergency Contact", key: "emergency_contact", type: "text" },
        { label: "Blackout Dates", key: "blackout_dates", type: "text" },
      ],
      booking: [
        { label: "Shift Start Time", key: "shift_start", type: "text" },
        { label: "Shift End Time", key: "shift_end", type: "text" },
        { label: "Reporting Manager", key: "reporting_manager", type: "text" },
        { label: "Uniform Requirement", key: "uniform", type: "text" },
        { label: "Attendance Checkpoint", key: "attendance_checkpoint", type: "text" },
      ],
      vendor: [
        { label: "Agency SPOC", key: "agency_spoc", type: "text" },
        { label: "Replacement Policy", key: "replacement_policy", type: "text" },
        { label: "Rate Card", key: "rate_card", type: "text" },
      ],
    },
    replacements: [
      ["Vendors & Procurement", "Staffing Agencies"], ["Equipment Master", "Role Master"], ["equipment master", "role master"],
      ["Master Registry", "Staff Registry"], ["Additions", "Add Staff"], ["Inventory", "Staff Roster"], ["inventory", "staff roster"], ["INVENTORY", "STAFF ROSTER"],
      ["Equipments", "Staff"], ["equipments", "staff"], ["EQUIPMENTS", "STAFF"],
      ["Asset Code", "Staff Code"], ["Serial Number", "Contract ID"], ["Warranty Expiring Soon", "Documents Pending"], ["Warranty", "ID Document"], ["warranty", "ID document"],
      ["Service Jobs", "Availability Follow-ups"], ["In Service", "On Hold"], ["in Service", "on Hold"], ["Returns due today", "Shift close-outs due"], ["under repair / maintenance", "availability / shift hold"],
      ["Equipment Utilization", "Staff Utilization"], ["Equipment in Service", "Availability Holds"], ["Equipment conflicts", "Staff conflicts"], ["3rd Party Equipment", "Freelance Staff"],
      ["Papers & QC", "Contracts & ID Docs"], ["Gate Pass", "Staff Deployment Sheet"], ["Job Card", "Staff Briefing Document"], ["Manpower Sheet", "Shift Assignment Sheet"], ["Damage Report", "Attendance / Incident Report"],
      ["Equipment", "Staff"], ["equipment", "staff"], ["EQUIPMENT", "STAFF"],
    ],
  }),
];

export function getBookingProfile(type = "equipment") {
  return BOOKING_PROFILES.find((profileItem) => profileItem.value === type) || BOOKING_PROFILES[0];
}

export function getEnabledDateTypes(type = "equipment") {
  return getBookingProfile(type).dateTypes || BASE_DATES;
}

export function isFeatureEnabled(type = "equipment", feature) {
  return Boolean(getBookingProfile(type).features?.[feature]);
}

export function applyBookingProfileText(text, type = "equipment") {
  let next = String(text || "");
  const replacements = [...getBookingProfile(type).replacements].sort((a, b) => b[0].length - a[0].length);
  for (const [from, to] of replacements) {
    next = next.replaceAll(from, to);
  }
  return next;
}
