const BASE_FEATURES = {
  maintenance: true,
  warranty: true,
  serviceJobs: true,
  returns: true,
  accessories: true,
  thirdParty: true,
  paxPrimary: false,
  contractTracking: false,
  consumableStock: true,
  riders: false,
  individualAvailability: false,
  attendance: false,
  conditionQc: true,
  dispatchReturn: true,
  subSpaces: false,
  warehouse: true,
};

const BASE_DATES = ["travel_day", "setup_date", "technical_date", "shoot_date", "off_day", "end_day", "return_day"];
const NO_RETURN_DATES = ["setup_date", "technical_date", "shoot_date", "off_day", "end_day"];

const COMMON = {
  eventTitle: "Event",
  bookingLabel: "Booking",
  crewLabel: "Crew",
  personnelLabel: "Personnel",
};

const equipmentTypes = [
  ["device", "Device - standalone bookable unit"],
  ["accessory", "Accessory - travels with a device"],
  ["kit", "Kit - named collection (auto-expands in booking)"],
  ["bundle", "Bundle - pre-packaged multi-device set"],
  ["third_party_equipment", "Third-Party Equipment - rented from vendor"],
  ["consumable", "Consumable - stock-depleted item"],
];

const baseReplacements = [
  ["Shoots", "Events"], ["shoots", "events"], ["SHOOTS", "EVENTS"],
  ["Shoot", "Event"], ["shoot", "event"], ["SHOOT", "EVENT"],
];

function profile({
  value,
  label,
  addLabel,
  registryLabel,
  resourceLabel,
  resourcePlural,
  utilizationLabel,
  complianceLabel,
  serviceLabel,
  serviceNavLabel,
  serviceItemLabel,
  conflictLabel,
  returnLabel,
  thirdPartyLabel,
  operationsLabel,
  vendorsLabel,
  features,
  itemTypes,
  replacements = [],
  extraFields = {},
  documents = {},
  dateTypes,
  workflow = {},
}) {
  return {
    ...COMMON,
    value,
    label,
    addLabel,
    registryLabel,
    resourceLabel,
    resourcePlural,
    utilizationLabel,
    complianceLabel,
    serviceLabel,
    serviceNavLabel: serviceNavLabel || "Service Jobs",
    serviceItemLabel: serviceItemLabel || "Service Job",
    conflictLabel,
    returnLabel,
    thirdPartyLabel,
    operationsLabel,
    vendorsLabel,
    features: { ...BASE_FEATURES, ...features },
    itemTypes,
    replacements: [...baseReplacements, ...replacements],
    extraFields,
    documents: {
      gatePass: "Gate Pass",
      jobCard: "Job Card",
      challan: "Road Challan",
      manpower: "Manpower Sheet",
      damage: "Damage Report",
      ...documents,
    },
    dateTypes: dateTypes || BASE_DATES,
    workflow,
  };
}

export const BOOKING_PROFILES = [
  profile({
    value: "equipment",
    label: "Equipment Booking",
    addLabel: "Additions",
    registryLabel: "Master Registry",
    resourceLabel: "Equipment",
    resourcePlural: "Equipment",
    utilizationLabel: "Equipment Utilization",
    complianceLabel: "Warranty Expiring Soon",
    serviceLabel: "Equipment in Service",
    serviceNavLabel: "Service & Repair Jobs",
    serviceItemLabel: "Service Job",
    conflictLabel: "Equipment conflicts",
    returnLabel: "Returns due today",
    thirdPartyLabel: "3rd Party Equipment",
    operationsLabel: "Papers & QC",
    vendorsLabel: "Vendors & Procurement",
    itemTypes: equipmentTypes,
    defaultCategories: ["Camera", "Lens", "Audio", "Lighting", "Power", "Support / Rigging", "Grip", "Storage / Media", "Transmission", "Cables / Accessories", "IT / Compute", "Other"],
    extraFields: {
      inventory: [
        { label: "Calibration notes", key: "calibration_notes", type: "text" },
        { label: "Insurance policy number", key: "insurance_policy", type: "text" },
        { label: "Replacement value (₹)", key: "replacement_value", type: "text" },
      ],
    },
  }),
  profile({
    value: "artist",
    label: "Artist Booking",
    addLabel: "Add Artist",
    registryLabel: "Artist Registry",
    resourceLabel: "Artist",
    resourcePlural: "Artists",
    utilizationLabel: "Artist Booking Load",
    complianceLabel: "Contracts / Riders Pending",
    serviceLabel: "Artist Holds",
    serviceNavLabel: "Contract Follow-ups",
    serviceItemLabel: "Artist Hold",
    conflictLabel: "Artist conflicts",
    returnLabel: "Follow-ups due today",
    thirdPartyLabel: "External Artists",
    operationsLabel: "Contracts & Riders",
    vendorsLabel: "Agencies & Managers",
    features: { maintenance: false, warranty: false, serviceJobs: false, returns: false, accessories: false, warehouse: false, contractTracking: true, riders: true, individualAvailability: true, conditionQc: false, dispatchReturn: false, consumableStock: false },
    itemTypes: [["solo_artist", "Solo Artist"], ["group_artist", "Band / Group"], ["artist_package", "Artist Package"], ["third_party_artist", "External Artist / Agency"]],
    defaultCategories: ["Bollywood", "Sufi / Ghazal", "Classical / Hindustani", "Folk / Regional", "Rock / Pop", "EDM / Electronic", "Jazz / Blues", "Hip-Hop / Rap", "Stand-up Comedy", "Dance / Choreography", "Instrumental", "Multi-genre"],
    dateTypes: NO_RETURN_DATES,
    documents: { gatePass: "Performance Call Sheet", jobCard: "Show Brief / Technical Rider", challan: "Travel Sheet", damage: "Cancellation / No-Show Report" },
    extraFields: {
      inventory: [
        { label: "Genre / Category", key: "genre", type: "select", options: ["", "Bollywood", "Sufi / Ghazal", "Classical / Hindustani", "Folk / Regional", "Rock / Pop", "EDM / Electronic", "Jazz / Blues", "Hip-Hop / Rap", "Stand-up Comedy", "Dance / Choreography", "Instrumental", "Multi-genre", "Other"] },
        { label: "Performance Type", key: "performance_type", type: "select", options: ["", "Live Singer", "Band / Group", "DJ", "Dancer", "Comedian", "Anchor / Host", "Motivational Speaker", "Classical Instrumentalist", "Magician / Illusionist", "Other"] },
        { label: "Primary Language", key: "language", type: "select", options: ["", "Hindi", "English", "Punjabi", "Tamil", "Telugu", "Kannada", "Marathi", "Bengali", "Gujarati", "Multi-lingual", "Other"] },
        { label: "Performance Duration", key: "performance_duration", type: "select", options: ["", "15 mins", "30 mins", "45 mins", "60 mins", "90 mins", "120 mins", "180 mins", "As per show requirement"] },
        { label: "Base Fee / Day Rate (₹)", key: "base_fee", type: "text" },
        { label: "Agent / Manager Contact", key: "agent_contact", type: "text" },
        { label: "Contract Expiry Date", key: "contract_expiry", type: "date" },
        { label: "Blackout Dates", key: "blackout_dates", type: "text" },
        { label: "Technical Rider Requirements", key: "technical_rider", type: "textarea" },
        { label: "Hospitality Rider Requirements", key: "hospitality_rider", type: "textarea" },
        { label: "Travel Requirements", key: "travel_requirements", type: "text" },
        { label: "Playlist / Set List Attachment", key: "playlist", type: "text" },
      ],
      booking: [
        { label: "Performance Slot", key: "performance_slot", type: "select", options: ["", "Opening Act", "Mid-show", "Headline / Closing", "Background Music", "Cocktail Hour", "Custom", "Other"] },
        { label: "Green Room Requirement", key: "green_room", type: "select", options: ["", "Not Required", "Basic Green Room", "VIP Green Room + Hospitality", "Separate Dressing Room"] },
        { label: "Soundcheck Time", key: "soundcheck_time", type: "text" },
        { label: "Hospitality Notes", key: "hospitality_notes", type: "textarea" },
      ],
      vendor: [
        { label: "Agency Commission (%)", key: "agency_commission", type: "text" },
        { label: "Manager Contact", key: "manager_contact", type: "text" },
        { label: "Contract Template", key: "contract_template", type: "text" },
      ],
    },
    replacements: [
      ["Vendors & Procurement", "Agencies & Managers"], ["Equipment Master", "Artist Category"], ["equipment master", "artist category"],
      ["Master Registry", "Artist Registry"], ["Additions", "Add Artist"], ["Inventory", "Artist Roster"], ["inventory", "artist roster"], ["INVENTORY", "ARTIST ROSTER"],
      ["Equipments", "Artists"], ["equipments", "artists"], ["EQUIPMENTS", "ARTISTS"],
      ["Asset Code", "Artist Code"], ["Serial Number", "Contract ID"], ["Warranty Expiring Soon", "Contracts / Riders Pending"],
      ["Warranty", "Contract"], ["warranty", "contract"], ["Service Jobs", "Contract Follow-ups"], ["In Service", "On Hold"], ["in Service", "on Hold"], ["in_service", "on_hold"],
      ["Returns due today", "Follow-ups due today"], ["under repair / maintenance", "availability / booking hold"], ["Warehouse", "Availability Group"], ["warehouse", "availability group"],
      ["Equipment Utilization", "Artist Booking Load"], ["3rd Party Equipment", "External Artists"], ["Equipment in Service", "Artist Holds"], ["Equipment conflicts", "Artist conflicts"],
      ["Papers & QC", "Contracts & Riders"], ["Gate Pass", "Performance Call Sheet"], ["Job Card", "Show Brief"], ["Damage / Missing", "Cancellation / No-Show"],
      ["Equipment", "Artist"], ["equipment", "artist"], ["EQUIPMENT", "ARTIST"],
    ],
  }),
  profile({
    value: "venue",
    label: "Venue Booking",
    addLabel: "Add Venue",
    registryLabel: "Venue Registry",
    resourceLabel: "Venue",
    resourcePlural: "Venues",
    utilizationLabel: "Venue Occupancy",
    complianceLabel: "Permits / Licenses Pending",
    serviceLabel: "Venue Maintenance Holds",
    serviceNavLabel: "Repairs & Maintenance",
    serviceItemLabel: "Repair Ticket",
    conflictLabel: "Venue conflicts",
    returnLabel: "Check-outs due today",
    thirdPartyLabel: "Partner Venues",
    operationsLabel: "Contracts & Permits",
    vendorsLabel: "Venue Partners",
    features: { warranty: false, returns: false, accessories: false, paxPrimary: true, contractTracking: true, attendance: true, subSpaces: true, dispatchReturn: false },
    itemTypes: [["indoor_venue", "Indoor Venue / Hall"], ["outdoor_venue", "Outdoor Venue / Lawn"], ["indoor_outdoor", "Indoor + Outdoor Venue"], ["partner_venue", "Partner Venue"]],
    defaultCategories: ["Banquet Hall", "Hotel Lawn / Garden", "Rooftop", "Farmhouse", "Beach / Waterfront", "Convention Centre", "Auditorium", "Open Ground", "Restaurant / Lounge", "Studio / Indoor Stage", "Mall Atrium", "Club / Bar"],
    dateTypes: NO_RETURN_DATES,
    documents: { gatePass: "Venue Access Letter", jobCard: "Event Layout / Setup Brief", challan: "Vendor Entry Pass", damage: "Venue Damage Report" },
    extraFields: {
      inventory: [
        { label: "Venue Type", key: "venue_type", type: "select", options: ["", "Banquet Hall", "Hotel Lawn / Garden", "Rooftop", "Farmhouse", "Beach / Waterfront", "Convention Centre", "Auditorium", "Open Ground", "Restaurant / Lounge", "Studio / Indoor Stage", "Mall Atrium", "Club / Bar", "Other"] },
        { label: "Indoor / Outdoor", key: "indoor_outdoor", type: "select", options: ["", "Indoor", "Outdoor", "Indoor + Outdoor", "Covered Outdoor"] },
        { label: "Capacity – Seated", key: "capacity_seated", type: "text" },
        { label: "Capacity – Theatre Style", key: "capacity_theatre", type: "text" },
        { label: "Capacity – Cocktail / Standing", key: "capacity_cocktail", type: "text" },
        { label: "Power Load Capacity (KW)", key: "power_kw", type: "text" },
        { label: "Amenities", key: "amenities", type: "select", options: ["", "AC + Parking + Generator", "AC + Parking", "AC + Generator", "AC Only", "Basic (No AC/Parking)", "Full AV + Lighting + Generator", "Other"] },
        { label: "Parking Capacity (vehicles)", key: "parking_capacity", type: "text" },
        { label: "Setup Time Buffer (hrs)", key: "setup_buffer", type: "text" },
        { label: "Breakdown Time Buffer (hrs)", key: "breakdown_buffer", type: "text" },
        { label: "Permit / License Number", key: "permit_number", type: "text" },
        { label: "Permit Expiry", key: "permit_expiry", type: "date" },
        { label: "Sub-spaces / Rooms", key: "subspaces", type: "text" },
        { label: "Floor Plan / Layout Notes", key: "layout_notes", type: "textarea" },
      ],
      booking: [
        { label: "Expected Guest Count", key: "guest_count", type: "text" },
        { label: "Layout Style", key: "layout_style", type: "select", options: ["", "Theatre", "Classroom", "Banquet (Round Tables)", "Cocktail / Standing", "U-Shape", "Boardroom", "Hollow Square", "Custom"] },
        { label: "Vendor Entry Window", key: "vendor_entry", type: "text" },
        { label: "Check-in Coordinator", key: "checkin_coordinator", type: "text" },
      ],
    },
    replacements: [
      ["Vendors & Procurement", "Venue Partners"], ["Equipment Master", "Venue Type"], ["equipment master", "venue type"],
      ["Master Registry", "Venue Registry"], ["Additions", "Add Venue"], ["Inventory", "Venue Spaces"], ["inventory", "venue spaces"], ["INVENTORY", "VENUE SPACES"],
      ["Equipments", "Venues"], ["equipments", "venues"], ["EQUIPMENTS", "VENUES"],
      ["Warehouse", "Venue Cluster"], ["warehouse", "venue cluster"], ["Asset Code", "Venue Code"], ["Serial Number", "License No."],
      ["Warranty Expiring Soon", "Permits / Licenses Pending"], ["Warranty", "Permit"], ["warranty", "permit"], ["Returns due today", "Check-outs due today"],
      ["Service Jobs", "Repairs & Maintenance"], ["Service Job", "Repair Ticket"], ["Create Repair Ticket", "Create Repair Ticket"], ["Create Service Job", "Create Repair Ticket"],
      ["Vendor / External Service", "Vendor / External Repair"], ["Inhouse Service", "Inhouse Repair"], ["Complete Service Job", "Complete Repair Ticket"],
      ["Service Bills", "Repair Bills"], ["Service Due", "Repair Due"], ["Related Service Job", "Related Repair Ticket"],
      ["Equipment Utilization", "Venue Occupancy"], ["Equipment in Service", "Venue Maintenance Holds"], ["Equipment conflicts", "Venue conflicts"], ["3rd Party Equipment", "Partner Venues"],
      ["Papers & QC", "Contracts & Permits"], ["Gate Pass", "Venue Access Letter"], ["Job Card", "Event Layout Brief"], ["Road Challan", "Vendor Entry Pass"],
      ["Equipment", "Venue"], ["equipment", "venue"], ["EQUIPMENT", "VENUE"],
    ],
  }),
  profile({
    value: "decor",
    label: "Decor Booking",
    addLabel: "Add Decor",
    registryLabel: "Decor Registry",
    resourceLabel: "Decor Item",
    resourcePlural: "Decor Items",
    utilizationLabel: "Decor Utilization",
    complianceLabel: "Condition Checks Due",
    serviceLabel: "Decor Under Repair",
    serviceNavLabel: "Repair & Refurbishment",
    serviceItemLabel: "Repair Ticket",
    conflictLabel: "Decor conflicts",
    returnLabel: "Returns due today",
    thirdPartyLabel: "Vendor Decor",
    operationsLabel: "Papers & Condition QC",
    vendorsLabel: "Decor Vendors",
    features: { warranty: false, contractTracking: false },
    itemTypes: [["decor_package", "Decor Package"], ["decor_item", "Decor Item"], ["decor_sub_item", "Decor Sub-item"], ["vendor_decor", "Vendor Decor"], ["consumable", "Consumable Decor"]],
    defaultCategories: ["Floral / Garden", "Royale / Mughal", "Contemporary / Modern", "Rustic / Vintage", "Minimalist", "Bohemian", "Beach / Coastal", "Festive / Traditional", "Corporate / Branded", "Fairytale / Princess", "Lighting & Ambiance", "Backdrop / Stage"],
    documents: { damage: "Condition Report" },
    extraFields: {
      inventory: [
        { label: "Decor Theme / Style", key: "decor_theme", type: "select", options: ["", "Floral / Garden", "Royale / Mughal", "Contemporary / Modern", "Rustic / Vintage", "Minimalist", "Bohemian", "Beach / Coastal", "Festive / Traditional", "Corporate / Branded", "Fairytale / Princess", "Lighting & Ambiance", "Backdrop / Stage", "Other"] },
        { label: "Material Type", key: "material_type", type: "select", options: ["", "Fabric / Draping", "Floral / Natural", "Wood", "Metal / Brass", "Plastic / Acrylic", "Paper / Cardboard", "Glass / Crystal", "LED / Neon Lights", "Thermocol / Foam", "Mixed", "Other"] },
        { label: "Color Palette", key: "color_palette", type: "text" },
        { label: "Condition Rating", key: "condition_rating", type: "select", options: ["", "Excellent", "Good", "Fair – Minor wear", "Needs Minor Repair", "Needs Major Repair"] },
        { label: "Fragility Level", key: "fragility", type: "select", options: ["", "Low – Durable", "Medium – Handle with care", "High – Fragile"] },
        { label: "Event Theme Tag", key: "event_theme_tag", type: "select", options: ["", "Wedding", "Sangeet", "Mehndi", "Birthday", "Baby Shower", "Corporate Gala", "Product Launch", "Conference", "Engagement", "Anniversary", "Other"] },
        { label: "Customization Notes", key: "customization", type: "textarea" },
      ],
      booking: [
        { label: "Theme Brief", key: "theme_brief", type: "textarea" },
        { label: "Installation Notes", key: "installation_notes", type: "textarea" },
        { label: "Strike / Removal Notes", key: "strike_notes", type: "text" },
      ],
    },
    replacements: [
      ["Vendors & Procurement", "Decor Vendors"], ["Equipment Master", "Decor Catalogue"], ["equipment master", "decor catalogue"],
      ["Master Registry", "Decor Registry"], ["Additions", "Add Decor"], ["Inventory", "Decor Inventory"], ["inventory", "decor inventory"], ["INVENTORY", "DECOR INVENTORY"],
      ["Equipments", "Decor Items"], ["equipments", "decor items"], ["EQUIPMENTS", "DECOR ITEMS"],
      ["Asset Code", "Decor Code"], ["Serial Number", "Batch / Set No."], ["Warranty Expiring Soon", "Condition Checks Due"], ["Warranty", "Condition"], ["warranty", "condition"],
      ["Service Jobs", "Repair & Refurbishment"], ["Service Job", "Repair Ticket"], ["Create Service Job", "Create Repair Ticket"],
      ["Vendor / External Service", "Vendor / External Repair"], ["Inhouse Service", "Inhouse Repair"], ["Complete Service Job", "Complete Repair Ticket"],
      ["Service Bills", "Repair Bills"], ["Service Due", "Repair Due"], ["Related Service Job", "Related Repair Ticket"],
      ["Equipment Utilization", "Decor Utilization"], ["Equipment in Service", "Decor Under Repair"], ["Equipment conflicts", "Decor conflicts"], ["3rd Party Equipment", "Vendor Decor"],
      ["Papers & QC", "Papers & Condition QC"], ["Damage Report", "Condition Report"], ["Equipment", "Decor Item"], ["equipment", "decor item"], ["EQUIPMENT", "DECOR ITEM"],
    ],
  }),
  profile({
    value: "catering",
    label: "Catering Booking",
    addLabel: "Add Catering",
    registryLabel: "Catering Registry",
    resourceLabel: "Menu",
    resourcePlural: "Menus",
    utilizationLabel: "Menu Booking Load",
    complianceLabel: "Menu / FSSAI Pending",
    serviceLabel: "Prep Holds",
    serviceNavLabel: "Prep Follow-ups",
    serviceItemLabel: "Prep Follow-up",
    conflictLabel: "Kitchen conflicts",
    returnLabel: "Final guest counts due",
    thirdPartyLabel: "Catering Partners",
    operationsLabel: "Menus & Compliance",
    vendorsLabel: "Catering Partners",
    features: { maintenance: false, warranty: false, serviceJobs: false, returns: false, accessories: false, warehouse: false, paxPrimary: true, contractTracking: true, conditionQc: false, dispatchReturn: false },
    itemTypes: [["catering_package", "Menu Package / Cuisine Station / Buffet Package"], ["consumable", "Consumable / Ingredient"], ["partner_caterer", "Partner Caterer"]],
    defaultCategories: ["North Indian", "South Indian", "Pan-Asian / Chinese", "Continental / Italian", "Mughlai / Awadhi", "Bengali", "Rajasthani / Gujarati", "Mediterranean", "Mexican", "Multi-Cuisine Buffet", "Bakery / Desserts", "Beverages / Bar"],
    dateTypes: NO_RETURN_DATES,
    documents: { gatePass: "Kitchen Brief", jobCard: "Banquet Event Order (BEO)", challan: "F&B Delivery Challan", manpower: "Service Staff Deployment", damage: "Not applicable" },
    extraFields: {
      inventory: [
        { label: "Cuisine Type", key: "cuisine_type", type: "select", options: ["", "North Indian", "South Indian", "Pan-Asian / Chinese", "Continental / Italian", "Mughlai / Awadhi", "Bengali", "Rajasthani / Gujarati", "Mediterranean", "Mexican", "Multi-Cuisine Buffet", "Bakery / Desserts", "Beverages / Bar", "Other"] },
        { label: "Meal Type", key: "meal_type", type: "select", options: ["", "Breakfast", "Brunch", "Lunch", "Hi-Tea / Snacks", "Dinner", "Cocktail Bites", "Full Day (B+L+D)", "Custom"] },
        { label: "Service Style", key: "service_style", type: "select", options: ["", "Buffet", "Plated / À La Carte", "Live Counters", "Family Style", "Cocktail / Finger Food", "Packed Meals", "Mix (Buffet + Live Counters)"] },
        { label: "Dietary Options", key: "dietary", type: "select", options: ["", "Pure Veg", "Veg + Non-Veg", "Vegan Available", "Jain Available", "Veg + Vegan + Jain", "Non-Veg Only"] },
        { label: "FSSAI / Batch Number", key: "fssai_number", type: "text" },
        { label: "Approx. Rate per Pax (₹)", key: "rate_per_pax", type: "text" },
        { label: "Tasting Notes", key: "tasting_notes", type: "textarea" },
        { label: "Ingredient / Allergen Notes", key: "allergen_notes", type: "textarea" },
      ],
      booking: [
        { label: "Pax Count", key: "pax_count", type: "text" },
        { label: "Meal Slot", key: "meal_slot", type: "select", options: ["", "Breakfast", "Lunch", "Hi-Tea", "Dinner", "All Day"] },
        { label: "Final Pax Count Deadline", key: "pax_deadline", type: "date" },
        { label: "Veg / Jain / Allergen Count", key: "veg_count", type: "text" },
        { label: "Live Counter Requirements", key: "live_counters", type: "text" },
        { label: "Service Staff Count", key: "service_staff", type: "text" },
        { label: "Tasting Session Date", key: "tasting_date", type: "date" },
      ],
      vendor: [
        { label: "FSSAI License Number", key: "fssai_license", type: "text" },
        { label: "Kitchen Contact", key: "kitchen_contact", type: "text" },
        { label: "Service Manager", key: "service_manager", type: "text" },
      ],
    },
    replacements: [
      ["Vendors & Procurement", "Catering Partners"], ["Equipment Master", "Menu Master"], ["equipment master", "menu master"],
      ["Master Registry", "Catering Registry"], ["Additions", "Add Catering"], ["Inventory", "Menu Packages"], ["inventory", "menu packages"], ["INVENTORY", "MENU PACKAGES"],
      ["Equipments", "Menus"], ["equipments", "menus"], ["EQUIPMENTS", "MENUS"],
      ["Asset Code", "Package Code"], ["Serial Number", "FSSAI / Batch No."], ["Warranty Expiring Soon", "Menu / FSSAI Pending"], ["Warranty", "FSSAI"], ["warranty", "FSSAI"],
      ["Service Jobs", "Prep Follow-ups"], ["In Service", "In Prep"], ["in Service", "in Prep"], ["Returns due today", "Final guest counts due"], ["under repair / maintenance", "menu / prep hold"],
      ["Equipment Utilization", "Menu Booking Load"], ["Equipment in Service", "Prep Holds"], ["Equipment conflicts", "Kitchen conflicts"], ["3rd Party Equipment", "Catering Partners"],
      ["Papers & QC", "Menus & Compliance"], ["Gate Pass", "Kitchen Brief"], ["Job Card", "Banquet Event Order"], ["Road Challan", "F&B Delivery Challan"], ["Manpower Sheet", "Service Staff Deployment"],
      ["Equipment", "Menu"], ["equipment", "menu"], ["EQUIPMENT", "MENU"],
    ],
  }),
  profile({
    value: "staffing",
    label: "Staffing Booking",
    addLabel: "Add Staff",
    registryLabel: "Staff Registry",
    resourceLabel: "Staff",
    resourcePlural: "Staff",
    utilizationLabel: "Staff Utilization",
    complianceLabel: "Documents Pending",
    serviceLabel: "Availability Holds",
    serviceNavLabel: "Availability Follow-ups",
    serviceItemLabel: "Availability Hold",
    conflictLabel: "Staff conflicts",
    returnLabel: "Shift close-outs due",
    thirdPartyLabel: "Freelance Staff",
    operationsLabel: "Contracts & ID Docs",
    vendorsLabel: "Staffing Agencies",
    features: { maintenance: false, warranty: false, serviceJobs: false, returns: false, accessories: false, warehouse: false, paxPrimary: true, contractTracking: true, individualAvailability: true, attendance: true, conditionQc: false, dispatchReturn: false, consumableStock: false },
    itemTypes: [["staff_role", "Staff Member / Role"], ["staff_team", "Staff Team"], ["shift_package", "Shift Package"], ["agency_staff", "Agency Staff"]],
    defaultCategories: ["Event Manager", "Floor Manager", "Registration / Help Desk", "Security / Bouncer", "Hostess / Host", "Sound Engineer", "Light Technician", "Stage Manager", "Photographer", "Videographer", "Serving Staff / Waiter", "Driver / Logistics", "MC / Anchor", "Coordinator", "Usher"],
    dateTypes: NO_RETURN_DATES,
    documents: { gatePass: "Staff Deployment Sheet", jobCard: "Staff Briefing Document", manpower: "Shift Assignment Sheet", damage: "Attendance / Incident Report" },
    extraFields: {
      inventory: [
        { label: "Role / Designation", key: "staff_role", type: "select", options: ["", "Event Manager", "Floor Manager", "Registration / Help Desk", "Security / Bouncer", "Hostess / Host", "Sound Engineer", "Light Technician", "Stage Manager", "Photographer", "Videographer", "Serving Staff / Waiter", "Driver / Logistics", "MC / Anchor", "Coordinator", "Usher", "Other"] },
        { label: "Shift Type", key: "shift_type", type: "select", options: ["", "Full Day (10+ hrs)", "Half Day (5–6 hrs)", "Morning Shift", "Evening / Night Shift", "Event Day Only", "Custom"] },
        { label: "Dress Code / Uniform", key: "dress_code", type: "select", options: ["", "Formal (Suit / Business)", "Semi-Formal (Smart Casual)", "Traditional / Ethnic", "Uniform (Company Provided)", "Black Tie / Evening Wear", "As per event theme"] },
        { label: "ID Document Type", key: "id_doc_type", type: "select", options: ["", "Aadhaar", "PAN", "Passport", "Voter ID", "Driving Licence"] },
        { label: "ID Document Number", key: "id_doc_number", type: "text" },
        { label: "ID Document Expiry", key: "id_expiry", type: "date" },
        { label: "Skills / Certifications", key: "skills", type: "text" },
        { label: "Daily / Hourly Rate (₹)", key: "rate", type: "text" },
        { label: "Background Check Status", key: "bg_check", type: "select", options: ["", "Not Required", "Pending", "Cleared", "Failed"] },
        { label: "Emergency Contact", key: "emergency_contact", type: "text" },
        { label: "Blackout Dates", key: "blackout_dates", type: "text" },
      ],
      booking: [
        { label: "Shift Start Time", key: "shift_start", type: "text" },
        { label: "Shift End Time", key: "shift_end", type: "text" },
        { label: "Reporting Manager", key: "reporting_manager", type: "text" },
        { label: "Uniform Requirement", key: "uniform", type: "text" },
        { label: "Attendance Checkpoint", key: "attendance_checkpoint", type: "text" },
      ],
      vendor: [
        { label: "Agency SPOC", key: "agency_spoc", type: "text" },
        { label: "Replacement Policy", key: "replacement_policy", type: "text" },
        { label: "Rate Card", key: "rate_card", type: "text" },
      ],
    },
    replacements: [
      ["Vendors & Procurement", "Staffing Agencies"], ["Equipment Master", "Role Master"], ["equipment master", "role master"],
      ["Master Registry", "Staff Registry"], ["Additions", "Add Staff"], ["Inventory", "Staff Roster"], ["inventory", "staff roster"], ["INVENTORY", "STAFF ROSTER"],
      ["Equipments", "Staff"], ["equipments", "staff"], ["EQUIPMENTS", "STAFF"],
      ["Asset Code", "Staff Code"], ["Serial Number", "Contract ID"], ["Warranty Expiring Soon", "Documents Pending"], ["Warranty", "ID Document"], ["warranty", "ID document"],
      ["Service Jobs", "Availability Follow-ups"], ["In Service", "On Hold"], ["in Service", "on Hold"], ["Returns due today", "Shift close-outs due"], ["under repair / maintenance", "availability / shift hold"],
      ["Equipment Utilization", "Staff Utilization"], ["Equipment in Service", "Availability Holds"], ["Equipment conflicts", "Staff conflicts"], ["3rd Party Equipment", "Freelance Staff"],
      ["Papers & QC", "Contracts & ID Docs"], ["Gate Pass", "Staff Deployment Sheet"], ["Job Card", "Staff Briefing Document"], ["Manpower Sheet", "Shift Assignment Sheet"], ["Damage Report", "Attendance / Incident Report"],
      ["Equipment", "Staff"], ["equipment", "staff"], ["EQUIPMENT", "STAFF"],
    ],
  }),
  profile({
    value: "security_agency",
    label: "Security Agency",
    addLabel: "Add Asset",
    registryLabel: "Equipment Registry",
    resourceLabel: "Security Asset",
    resourcePlural: "Security Assets",
    utilizationLabel: "Asset Deployment Rate",
    complianceLabel: "Renewals / Certifications Due",
    serviceLabel: "Assets in Maintenance",
    serviceNavLabel: "Maintenance Jobs",
    serviceItemLabel: "Maintenance Job",
    conflictLabel: "Deployment conflicts",
    returnLabel: "Returns due today",
    thirdPartyLabel: "Contracted Assets",
    operationsLabel: "Deployment Papers",
    vendorsLabel: "Security Vendors",
    features: { maintenance: true, warranty: true, serviceJobs: true, returns: true, accessories: true, warehouse: true, paxPrimary: false, contractTracking: true, individualAvailability: false, attendance: false, conditionQc: true, dispatchReturn: true, consumableStock: true },
    itemTypes: [["detection_equipment", "Detection Equipment"], ["communication", "Communication Device"], ["surveillance", "Surveillance Equipment"], ["crowd_management", "Crowd Management"], ["uniform", "Uniform / PPE"], ["vehicle", "Patrol Vehicle"]],
    defaultCategories: ["Detection", "Communication", "Surveillance", "Crowd Management", "Uniform", "Safety", "Vehicle", "Documentation", "Weapon / Baton", "Other"],
    documents: { gatePass: "Deployment Order", jobCard: "Security Briefing", manpower: "Guard Deployment Sheet", damage: "Incident Report" },
    extraFields: {
      inventory: [
        { label: "License / Cert Number", key: "cert_number", type: "text" },
        { label: "Cert Expiry Date", key: "cert_expiry", type: "date" },
        { label: "Frequency / Channel", key: "frequency", type: "text" },
        { label: "CAPF / PSARA Compliant", key: "psara", type: "select", options: ["", "Yes", "No", "Not Applicable"] },
        { label: "Calibration Due", key: "calibration_due", type: "date" },
      ],
      booking: [
        { label: "Threat Level", key: "threat_level", type: "select", options: ["", "Low", "Medium", "High", "VIP / Critical"] },
        { label: "Post / Zone Assigned", key: "post_zone", type: "text" },
        { label: "Supervisor In-charge", key: "supervisor", type: "text" },
        { label: "Nearest Police Station", key: "police_station", type: "text" },
        { label: "Emergency SOP", key: "emergency_sop", type: "text" },
      ],
      vendor: [
        { label: "PSARA License No", key: "psara_no", type: "text" },
        { label: "PSARA Expiry", key: "psara_expiry", type: "date" },
        { label: "No. of Guards on Roll", key: "guard_count", type: "text" },
        { label: "Armed / Unarmed", key: "armed", type: "select", options: ["", "Armed", "Unarmed", "Both"] },
      ],
    },
    replacements: [
      ["Vendors & Procurement", "Security Vendors"], ["Equipment Master", "Asset Master"], ["equipment master", "asset master"],
      ["Master Registry", "Equipment Registry"], ["Additions", "Add Asset"], ["Inventory", "Security Assets"], ["inventory", "security assets"], ["INVENTORY", "SECURITY ASSETS"],
      ["Equipments", "Security Assets"], ["equipments", "security assets"], ["EQUIPMENTS", "SECURITY ASSETS"],
      ["Asset Code", "Asset Code"], ["Serial Number", "Serial / Cert No"], ["Warranty Expiring Soon", "Renewals / Certs Due"], ["Warranty", "Certification"], ["warranty", "certification"],
      ["Service Jobs", "Maintenance Jobs"], ["Returns due today", "Returns due today"],
      ["Equipment Utilization", "Asset Deployment Rate"], ["Equipment in Service", "Assets in Maintenance"], ["Equipment conflicts", "Deployment conflicts"], ["3rd Party Equipment", "Contracted Assets"],
      ["Papers & QC", "Deployment Papers"], ["Gate Pass", "Deployment Order"], ["Job Card", "Security Briefing"], ["Damage Report", "Incident Report"],
      ["Equipment", "Security Asset"], ["equipment", "security asset"], ["EQUIPMENT", "SECURITY ASSET"],
    ],
  }),
  profile({
    value: "photography_videography",
    label: "Photography & Videography",
    addLabel: "Add Equipment",
    registryLabel: "Camera & Gear Registry",
    resourceLabel: "Camera / Gear",
    resourcePlural: "Camera & Gear",
    utilizationLabel: "Gear Utilization",
    complianceLabel: "Warranty Expiring Soon",
    serviceLabel: "Gear in Service",
    serviceNavLabel: "Service & Calibration Jobs",
    serviceItemLabel: "Service Job",
    conflictLabel: "Gear conflicts",
    returnLabel: "Returns due today",
    thirdPartyLabel: "Rented Gear",
    operationsLabel: "Dispatch & Returns",
    vendorsLabel: "Equipment Vendors",
    features: { maintenance: true, warranty: true, serviceJobs: true, returns: true, accessories: true, warehouse: true, paxPrimary: false, contractTracking: false, individualAvailability: false, attendance: false, conditionQc: true, dispatchReturn: true, consumableStock: true },
    itemTypes: [["camera_body", "Camera Body"], ["lens", "Lens"], ["lighting", "Lighting"], ["stabilizer", "Stabilizer / Gimbal"], ["drone", "Drone"], ["support", "Support / Tripod"], ["audio", "Audio"], ["storage", "Storage / Media"]],
    defaultCategories: ["Camera", "Lens", "Lighting", "Stabilizer", "Drone", "Support", "Audio", "Storage", "Monitor", "Other"],
    documents: { gatePass: "Gear Dispatch Note", jobCard: "Shoot Brief", manpower: "Crew Call Sheet", damage: "Damage Report" },
    extraFields: {
      inventory: [
        { label: "Sensor Type", key: "sensor_type", type: "select", options: ["", "Full Frame", "APS-C", "Micro Four Thirds", "Medium Format", "1-inch", "Other"] },
        { label: "Mount Type", key: "mount_type", type: "text" },
        { label: "Max Resolution", key: "resolution", type: "text" },
        { label: "Firmware Version", key: "firmware", type: "text" },
        { label: "Calibration Due", key: "calibration_due", type: "date" },
        { label: "Insurance Value (₹)", key: "insured_value", type: "text" },
      ],
      booking: [
        { label: "Shoot Type", key: "shoot_type", type: "select", options: ["", "Wedding", "Corporate", "Product", "Fashion", "Concert", "Documentary", "Commercial", "Other"] },
        { label: "Output Format", key: "output_format", type: "select", options: ["", "4K RAW", "4K H.265", "1080p", "RAW Stills", "JPEG", "Mixed"] },
        { label: "Delivery Deadline", key: "delivery_deadline", type: "date" },
        { label: "Client Drive Required", key: "client_drive", type: "text" },
      ],
      vendor: [
        { label: "Specialisation", key: "specialisation", type: "text" },
        { label: "Authorised Service Centre", key: "asc", type: "text" },
      ],
    },
    replacements: [
      ["Vendors & Procurement", "Equipment Vendors"], ["Equipment Master", "Gear Master"], ["equipment master", "gear master"],
      ["Equipments", "Camera & Gear"], ["equipments", "camera & gear"], ["EQUIPMENTS", "CAMERA & GEAR"],
      ["Warranty Expiring Soon", "Warranty / Calibration Due"], ["Service Jobs", "Service & Calibration"],
      ["Equipment Utilization", "Gear Utilization"], ["Equipment in Service", "Gear in Service"], ["Equipment conflicts", "Gear conflicts"],
      ["Papers & QC", "Dispatch & Returns"], ["Gate Pass", "Gear Dispatch Note"], ["Job Card", "Shoot Brief"], ["Damage Report", "Damage Report"],
      ["Equipment", "Gear"], ["equipment", "gear"], ["EQUIPMENT", "GEAR"],
    ],
  }),
  profile({
    value: "cars_logistics",
    label: "Cars & Logistics",
    addLabel: "Add Vehicle",
    registryLabel: "Fleet Registry",
    resourceLabel: "Vehicle",
    resourcePlural: "Fleet",
    utilizationLabel: "Fleet Utilization",
    complianceLabel: "PUC / Insurance Expiring",
    serviceLabel: "Vehicles in Service",
    serviceNavLabel: "Maintenance Jobs",
    serviceItemLabel: "Maintenance Job",
    conflictLabel: "Fleet conflicts",
    returnLabel: "Returns due today",
    thirdPartyLabel: "Hired Vehicles",
    operationsLabel: "Trip & Delivery Papers",
    vendorsLabel: "Transport Vendors",
    features: { maintenance: true, warranty: true, serviceJobs: true, returns: true, accessories: true, warehouse: false, paxPrimary: true, contractTracking: false, individualAvailability: false, attendance: false, conditionQc: true, dispatchReturn: true, consumableStock: false },
    itemTypes: [["luxury_car", "Luxury Car"], ["suv", "SUV / MUV"], ["mini_bus", "Mini Bus / Tempo"], ["truck", "Truck / Container"], ["utility", "Utility Vehicle"], ["tracking", "Tracking Device"], ["material_handling", "Material Handling"]],
    defaultCategories: ["Luxury Car", "SUV", "Mini Bus", "Truck", "Utility", "Tracking", "Material Handling", "Other"],
    documents: { gatePass: "Trip Sheet / Gate Pass", jobCard: "Vehicle Deployment Order", manpower: "Driver Assignment Sheet", damage: "Accident / Damage Report" },
    extraFields: {
      inventory: [
        { label: "Registration Number", key: "reg_number", type: "text" },
        { label: "RC Expiry Date", key: "rc_expiry", type: "date" },
        { label: "Insurance Expiry", key: "insurance_expiry", type: "date" },
        { label: "PUC Expiry", key: "puc_expiry", type: "date" },
        { label: "Seating Capacity", key: "seating", type: "text" },
        { label: "Fuel Type", key: "fuel_type", type: "select", options: ["", "Petrol", "Diesel", "CNG", "Electric", "Hybrid"] },
        { label: "Odometer (km)", key: "odometer", type: "text" },
        { label: "AC / Non-AC", key: "ac", type: "select", options: ["", "AC", "Non-AC"] },
      ],
      booking: [
        { label: "Pickup Location", key: "pickup_location", type: "text" },
        { label: "Drop Location", key: "drop_location", type: "text" },
        { label: "Estimated KM", key: "estimated_km", type: "text" },
        { label: "Driver Name", key: "driver_name", type: "text" },
        { label: "Driver Phone", key: "driver_phone", type: "text" },
      ],
      vendor: [
        { label: "Fleet Size", key: "fleet_size", type: "text" },
        { label: "Coverage States", key: "coverage", type: "text" },
        { label: "GPS Enabled", key: "gps_enabled", type: "select", options: ["", "Yes", "No"] },
      ],
    },
    replacements: [
      ["Vendors & Procurement", "Transport Vendors"], ["Equipment Master", "Vehicle Master"], ["equipment master", "vehicle master"],
      ["Equipments", "Fleet"], ["equipments", "fleet"], ["EQUIPMENTS", "FLEET"],
      ["Warranty Expiring Soon", "PUC / Insurance Expiring"], ["Service Jobs", "Maintenance Jobs"],
      ["Equipment Utilization", "Fleet Utilization"], ["Equipment in Service", "Vehicles in Service"], ["Equipment conflicts", "Fleet conflicts"],
      ["Papers & QC", "Trip & Delivery Papers"], ["Gate Pass", "Trip Sheet / Gate Pass"], ["Job Card", "Vehicle Deployment Order"], ["Damage Report", "Accident / Damage Report"],
      ["Equipment", "Vehicle"], ["equipment", "vehicle"], ["EQUIPMENT", "VEHICLE"],
    ],
  }),
  profile({
    value: "props_dresses",
    label: "Props & Dresses",
    addLabel: "Add Item",
    registryLabel: "Props & Wardrobe Registry",
    resourceLabel: "Prop / Outfit",
    resourcePlural: "Props & Outfits",
    utilizationLabel: "Inventory Utilization",
    complianceLabel: "Dry-clean / Repair Due",
    serviceLabel: "Items in Repair",
    serviceNavLabel: "Repair & Cleaning Jobs",
    serviceItemLabel: "Repair Job",
    conflictLabel: "Item conflicts",
    returnLabel: "Returns due today",
    thirdPartyLabel: "Borrowed Items",
    operationsLabel: "Handover & Returns",
    vendorsLabel: "Costume & Props Vendors",
    features: { maintenance: true, warranty: false, serviceJobs: true, returns: true, accessories: true, warehouse: true, paxPrimary: false, contractTracking: false, individualAvailability: false, attendance: false, conditionQc: true, dispatchReturn: true, consumableStock: false },
    itemTypes: [["bridal_wear", "Bridal Wear"], ["groom_wear", "Groom Wear"], ["traditional_wear", "Traditional Wear"], ["costume", "Themed Costume"], ["prop", "Prop / Decor Item"], ["accessories", "Accessories & Jewellery"]],
    defaultCategories: ["Bridal Wear", "Groom Wear", "Traditional Wear", "Themed Costume", "Vintage Props", "Backdrop Props", "Decor Props", "Accessories", "Jewellery", "Other"],
    documents: { gatePass: "Handover Checklist", jobCard: "Styling Brief", manpower: "Dresser Assignment", damage: "Damage / Stain Report" },
    extraFields: {
      inventory: [
        { label: "Size / Measurements", key: "size", type: "text" },
        { label: "Colour", key: "colour", type: "text" },
        { label: "Fabric / Material", key: "fabric", type: "text" },
        { label: "Designer / Brand", key: "designer", type: "text" },
        { label: "Dry-clean Due", key: "dry_clean_due", type: "date" },
        { label: "Rental Value / Day (₹)", key: "rental_value", type: "text" },
        { label: "Replacement Value (₹)", key: "replacement_value", type: "text" },
      ],
      booking: [
        { label: "Event / Shoot Theme", key: "shoot_theme", type: "text" },
        { label: "Stylist Name", key: "stylist_name", type: "text" },
        { label: "Alterations Needed", key: "alterations", type: "select", options: ["", "None", "Minor", "Major"] },
        { label: "Security Deposit (₹)", key: "security_deposit", type: "text" },
      ],
      vendor: [
        { label: "Speciality", key: "speciality", type: "text" },
        { label: "Designer Labels Stocked", key: "designers", type: "text" },
        { label: "Alteration Service", key: "alteration_service", type: "select", options: ["", "Yes", "No"] },
      ],
    },
    replacements: [
      ["Vendors & Procurement", "Costume & Props Vendors"], ["Equipment Master", "Items Master"], ["equipment master", "items master"],
      ["Equipments", "Props & Outfits"], ["equipments", "props & outfits"], ["EQUIPMENTS", "PROPS & OUTFITS"],
      ["Warranty Expiring Soon", "Dry-clean / Repair Due"], ["Service Jobs", "Repair & Cleaning Jobs"],
      ["Equipment Utilization", "Inventory Utilization"], ["Equipment in Service", "Items in Repair"], ["Equipment conflicts", "Item conflicts"],
      ["Papers & QC", "Handover & Returns"], ["Gate Pass", "Handover Checklist"], ["Job Card", "Styling Brief"], ["Damage Report", "Damage / Stain Report"],
      ["Equipment", "Item"], ["equipment", "item"], ["EQUIPMENT", "ITEM"],
    ],
  }),
];

export function getBookingProfile(type = "equipment") {
  return BOOKING_PROFILES.find((profileItem) => profileItem.value === type) || BOOKING_PROFILES[0];
}

export function getEnabledDateTypes(type = "equipment") {
  return getBookingProfile(type).dateTypes || BASE_DATES;
}

export function isFeatureEnabled(type = "equipment", feature) {
  return Boolean(getBookingProfile(type).features?.[feature]);
}

export function applyBookingProfileText(text, type = "equipment") {
  let next = String(text || "");
  const replacements = [...getBookingProfile(type).replacements].sort((a, b) => b[0].length - a[0].length);
  for (const [from, to] of replacements) {
    next = next.replaceAll(from, to);
  }
  return next;
}
